language: node_js
deploy:
  provider: heroku
  api_key:
    secure: "whoops"
before_install:
  # install v6.x of nodejs
   - nvm install 6
  #install yarn globally
   - npm install -g yarn
  # yarn install is like npm install
   - yarn install