language: node_js
env:
  - NODE_ENV=test
services:
  - postgresql
addons:
  postgresql: "9.6"
cache: yarn
before_script:
  - psql -c 'create database thesis_test;' -U postgres
  - yarn knex migrate:latest
script:
  - 'yarn server-test'
  - 'yarn front-test'
deploy:
  provider: heroku
  api_key:
    secure: "whoops"
node_js:
  - "8"
  - "7"
  - "6"
