language: node_js
env:
  - DB=postgres
  - NODE_ENV=test
services: 
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database thesis_test'; -U postgres
  - yarn knex migrate:latest 
  - yarn knex seed:run
deploy:
  provider: heroku
  api_key:
    secure: "whoops"
node_js:
  - "8"
  - "7"
  - "6"
  - "5"